language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
install:
    - pip install django
    - pip install django-forms-fieldset
    - pip install coverage
before_script:
    - python -m pip install --upgrade pip
    - python examples/project/manage.py migrate
script:
    - cd examples/project/ && coverage run --source='.' manage.py test
    - coverage report
